### ISSUE TITLE
Firefox Add-on support

### ISSUE THREAD

**Issue by rishi255** [nisarg0/Kontest-Reminder#2]
Since the extension is currently just for Chrome, it would be nice to have this on the Firefox add-on store as well. 

Most of the commands with the `chrome` namespace will work, but minor changes and compatibility checks using the [Firefox Extension Test Website](https://www.extensiontest.com/) have to be made.

I'm working on it currently, and I'll update once it's done.

**Comment by nisarg0** [comment]
That would be great!!! If you face any issues do let our team know.

**Comment by nisarg0** [comment]
Great work @rishi255.
